Добавлена функция bitmap__create
vdyadov/Bitmap pull request #12
Opened 2021-06-21 18:26 UTC by DmitryRozhdenko

2021-06-22 03:39 UTC, Varumithu requested changes

2021-06-22 03:39 UTC, Varumithu commented on src/bitmap.c
> +		 // недо­статочно памяти  для выделения битовой карты
Форматирование. У тебя два таба здесь, четыре пробела чуть раньше. Если у тебя один отступ - четыре пробела, то двойной отступ должен быть восемь пробелов (а не два таба). В начале функции 4 пробела для одного отступа, а после первой проверки условия, внезапно, 1 таб.

2021-06-22 16:56 UTC, vdyadov commented on src/bitmap.c
> +    unsigned short size_mashina;
Тут надо инициализировать переменные

2021-06-23 07:15 UTC, Varumithu requested changes

2021-06-23 07:15 UTC, Varumithu commented on include/bitmap.h
> +int bitmap__setNull_bit(
Во первых, она должна быть в отдельной ветке. Этот пулл реквест - для функции создания, всего остального в нем быть не должно.

Во-вторых, она должна называться bitmap__clear_bit или как то так.

2021-06-23 07:15 UTC, Varumithu commented on include/bitmap.h
> +int bitmap__creator(
Функции - это глаголы, а не существительные. bitmap__create должно быть название, а не creator

2021-06-23 07:15 UTC, Varumithu commented on src/bitmap.c
> +	p_bitmap->magic = BITMAP_MAGIC;
Форматирование. Отступы одного уровня должны быть одинаковыми, а у тебя здесь один символ табуляции, 4 пробела до этого. Я уже писал об этой проблеме.

2021-06-23 07:15 UTC, Varumithu commented on src/bitmap.c
> +    unsigned short bit_offset = 0;
Форматирование. Ну видно же невооруженным глазом, что отступы разные. + Эта функция должна быть в другой ветке.

2021-06-23 07:15 UTC, Varumithu commented on src/bitmap.c
> +    mask = (unsigned long) (1 << bit_offset);
Это работает? Ты сдвигаешь единицу справа влево. Представим, что у нас биты храняться в однобайтовых переменных, надо занулить бит с индексом 1. В результате:
bit_offset == 1
mask == 00000001 << 1 == 00000010

А должно быть 01000000.

2021-06-23 07:18 UTC, Varumithu commented
А еще тут теперь два коммита, их надо склеить.

2021-06-23 19:04 UTC, vdyadov commented
#

2021-06-23 19:04 UTC, closed without merging